# Set all versions
CUSTOM_BUILD_TYPE ?= UNOFFICIAL

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

CUSTOM_PLATFORM_VERSION := 9.0
CUSTOM_FEATURE_PACK := Explorer

TARGET_PRODUCT_SHORT := $(subst simplix_,,$(CUSTOM_BUILD))

CUSTOM_BUILD_TYPE := OFFICIAL

CUSTOM_VERSION := SimplixOne-$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_FEATURE_PACK)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := Pie
ROM_FINGERPRINT := SimplixOne-/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)

CUSTOM_PROPERTIES := \
    com.simplixone.version=$(CUSTOM_VERSION) \
    com.simplixone.build_date=$(CUSTOM_BUILD_DATE) \
    com.simplixone.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    com.simplixone.build_type=$(CUSTOM_BUILD_TYPE) \
    com.simplixone.fingerprint=$(ROM_FINGERPRINT) \
    com.simplixone.feature_pack=$(CUSTOM_FEATURE_PACK)
